[project]
name = "netnetty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-whois",
    "dnspython",
    "google-genai",
    "argparse>=1.4.0",
    "typing>=3.10.0.0",
]
